# Generated by Django 4.0 on 2022-08-08 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_rename_forum_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='goruldu',
            field=models.ManyToManyField(related_name='goruldu', to=settings.AUTH_USER_MODEL),
        ),
    ]
