# Generated by Django 4.0 on 2022-08-10 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_form_goruldu'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='like',
            field=models.ManyToManyField(related_name='form_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=160)),
                ('image', models.ImageField(default='default.jpg', upload_to='profilePhotos')),
                ('create', models.DateTimeField(auto_now=True)),
                ('edit', models.DateTimeField(auto_now_add=True)),
                ('formanswerlike', models.ManyToManyField(related_name='form_answer_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
