# Generated by Django 4.0 on 2022-08-11 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_form_goruldu_alter_form_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='goruldu',
            field=models.ManyToManyField(blank=True, related_name='goruldu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='form_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
