# Generated by Django 4.0 on 2022-08-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0006_alter_form_goruldu_alter_form_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='No info was given.', max_length=160)),
                ('profile_pic', models.ImageField(blank=True, default='default_pp.png', null=True, upload_to='')),
                ('create', models.DateTimeField(auto_now=True)),
                ('edit', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='profile_followers', to='base.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
