# Generated by Django 4.0 on 2022-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_pic',
            field=models.ImageField(blank=True, default='default_bgp.png', null=True, upload_to=''),
        ),
    ]
