# Generated by Django 4.0 on 2022-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_background_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_pic',
            field=models.ImageField(blank=True, default='default_bgp.png', null=True, upload_to='background_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pp.png', null=True, upload_to='profile_pic'),
        ),
    ]
