# Generated by Django 4.0 on 2022-08-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_profile_background_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='form',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formanswer',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='form_like', to='base.Profile'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='formanswerlike',
            field=models.ManyToManyField(related_name='form_answer_like', to='base.Profile'),
        ),
    ]
