# Generated by Django 4.0 on 2022-08-21 10:13

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_form_level_form_lft_form_parent_form_rght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='parent',
        ),
        migrations.AddField(
            model_name='formanswer',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='base.formanswer'),
        ),
    ]
