# Generated by Django 4.0 on 2022-08-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_form_parent_formanswer_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='level',
        ),
        migrations.RemoveField(
            model_name='form',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='form',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='form',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='formanswer',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formanswer',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formanswer',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formanswer',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
