# Generated by Django 4.0 on 2022-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_form_level_remove_form_lft_remove_form_rght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='formanswerlike',
            field=models.ManyToManyField(null=True, related_name='form_answer_like', to='base.Profile'),
        ),
    ]
