# Generated by Django 4.0 on 2022-08-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_formanswer_formanswerlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.form'),
            preserve_default=False,
        ),
    ]
