# Generated by Django 4.0 on 2022-08-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_formanswer_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formanswer',
            name='form',
        ),
    ]
