# Generated by Django 4.0 on 2022-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_formanswer_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_pic',
            field=models.ImageField(blank=True, default='background_pic/default_bgp.png', null=True, upload_to='background_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_pp.png', null=True, upload_to='profile_pic'),
        ),
    ]
