# Generated by Django 4.0 on 2022-08-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_formanswer_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='formanswerlike',
            field=models.ManyToManyField(blank=True, null=True, related_name='form_answer_like', to='base.Profile'),
        ),
    ]
