# Generated by Django 4.0 on 2022-08-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_profile_background_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='profilePhotos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='formanswer',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilePhotos'),
        ),
    ]
