# Generated by Django 4.0 on 2022-08-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_form_image_alter_formanswer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profilePhotos', verbose_name='Image'),
        ),
    ]
